version: '3.0'
services:

  web:
    build:
      dockerfile: marketplace/Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    command: sh -c "python manage.py start_listening & python manage.py run_servers"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      kafka:
        condition: service_started
    env_file:
      - .env
    volumes:
      - code:/app/backend
      - task_data:/app/backend/tasks_data
    networks:
      - kafkanet
      - net

  kafka:
    image: "confluentinc/cp-kafka:6.2.1"
    hostname: "kafka"
    ports:
      - "9092:9092"
    env_file:
      - kafka.env
    depends_on:
      zookeeper:
        condition: service_started
    networks:
      - kafkanet

  zookeeper:
    image: "bitnami/zookeeper:3.4.14"
    hostname: "zookeeper"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafkanet

  bot:
    build:
      dockerfile: ./bot/Dockerfile
    ports:
      - "8002:8002"
    command: >
      sh -c "python bot/bot.py"
    env_file:
      - bot/bot.env
    depends_on:
      - web
      - redis
      - kafka
    networks:
      - kafkanet
    volumes:
      - ./bot:/bot

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - 6379:6379
    hostname: redis
    networks:
      - net

  worker:
    build:
      dockerfile: marketplace/Dockerfile
    hostname: worker
    command: sh -c "cd marketplace && celery -A celery_app.app worker --loglevel=info --concurrency=10 -n worker2@%h & celery -A celery_app.app worker --loglevel=info --concurrency=10 -n worker3@%h & celery -A celery_app.app worker --loglevel=info --concurrency=10 -n worker5@%h & tail -f /dev/null"
    env_file:
      - .env
    networks:
      - net
    depends_on:
      - redis
      - db
    volumes:
      - code:/app/backend
      - task_data:/app/backend/tasks_data

  flower:
    build:
      dockerfile: marketplace/Dockerfile
    hostname: flower
    entrypoint: celery
    command: sh -c "cd marketplace && -A celery_app.app flower"
    env_file:
      - .env
    volumes:
      - code:/app/backend
      - task_data:/app/backend/tasks_data
    networks:
      - net
    depends_on:
      - redis
      - db
    ports:
      - 5555:5555


  db:
    container_name: postgres_drf
    image: postgres:15.1-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - net
    hostname: postgres

volumes:
  code:
  bot:
  task_data:

networks:
  kafkanet:
    driver: bridge
  net:
    driver: bridge
